# Generated by Django 3.2.8 on 2021-11-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.basemodel')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('end_data', models.DateField()),
                ('status', models.CharField(choices=[(1, 'open'), (0, 'close')], max_length=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='users.user')),
            ],
            bases=('users.basemodel',),
        ),
    ]
